import { MD3LightTheme } from 'react-native-paper';

export const AppTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#5B3EBF',
    onPrimary: '#FFFFFF',
    primaryContainer: '#EDE5FF',
    onPrimaryContainer: '#180060',
    secondary: '#006D77',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#D0F8FA',
    onSecondaryContainer: '#001F24',
    tertiary: '#C0395B',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#FFD9E2',
    onTertiaryContainer: '#3E001D',
    error: '#B3261E',
    onError: '#FFFFFF',
    errorContainer: '#F9DEDC',
    onErrorContainer: '#410E0B',
    background: '#FDFBFF',
    onBackground: '#1C1B1F',
    surface: '#FFFBFE',
    onSurface: '#1C1B1F',
    surfaceVariant: '#E7E0EC',
    onSurfaceVariant: '#49454F',
    outline: '#7A757F',
    outlineVariant: '#CAC4D0',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#313033',
    inverseOnSurface: '#F4EFF4',
    inversePrimary: '#CFBCFF',
    elevation: {
      ...MD3LightTheme.colors.elevation,
      level0: 'transparent',
      level1: '#F5EEFF',
      level2: '#EFE6FF',
      level3: '#E9DDFF',
      level4: '#E7DBFF',
      level5: '#E3D6FF',
    },
  },
} as const;
